bench/utils.py

FreeBSD crontab(1) needs a "-" to read from stdin

FreeBSD crontab(1) needs a "-" to read from stdin

---

bench/utils.py
setup.py

bump up the version to the latest release

bump up the version to the latest release

---

install_scripts/setup_frappe.sh

missing nodejs npm

---

install_scripts/setup_frappe.sh

https://discuss.erpnext.com/t/error-while-installing-frappe-bench/8348

[fixes] wkhtmltopdf deb installation fix for vivid

---

README.md
install_scripts/setup_frappe.sh

Reverts frappe/bench#159
@yashodhank Discussed with @pdvyas that changing swappiness is not a good idea. He will elaborate.

Revert "Automate swap partition setup for centos / ubuntu / debian servers"

---

README.md

Better clarity about the differences between Production and Development environments.

Updated text to make a clear distinction between Production and Development environments

---

bench/tests/test_init.py

- Added test case for drop-site command on bench.
***This should be merged after frappe/frappe#1720***

Test drop site

---

bench/tests/test_init.py

- Fixed the test case for drop site.

[Fix] Fixed drop site test case

---

README.md

Sync with https://github.com/frappe/frappe/pull/1738

Fixed links for Guide

---

bench/app.py

Fix for https://github.com/frappe/frappe/issues/1737
Sync with https://github.com/frappe/frappe/pull/1739

Added validation for App Name

---

bench/app.py
bench/commands/make.py
bench/tests/test_init.py
bench/utils.py
vm/ansible/library/bench.py

Removed get-app app-name argument

---

README.md

Manually merged https://github.com/frappe/bench/pull/198
Thanks to @ckosiegbu

Added info for OSX

---

playbooks/install.py

Fixed #233 
- Added option to mention bench_repo_url.
- Updated some routines.

[Fix] Ansible installer fails to install wkhtmltopdf with newer ansible version

---

bench/config/common_site_config.py

Fix for : https://github.com/frappe/bench/issues/241

DNS Multitenancy by default

---

playbooks/install.py

Theoretical fix for ~~Mac OSX~~ macOS as well :sweat_smile:

[fix] fixed setuptools for ubuntu

---

bench/cli.py
bench/commands/__init__.py
bench/commands/setup.py
bench/commands/utils.py
bench/config/production_setup.py
bench/tests/test_setup_production.py

Command to disable production in bench

---

bench/app.py
bench/commands/__init__.py
bench/commands/make.py
bench/tests/test_init.py
bench/utils.py

Todo 
Possible improvements : 
Check for existing apps in sites more efficiently
Better method to check for valid site

Added command to remove app

---

bench/patches/v4/update_node.py
playbooks/develop/centos.yml
playbooks/develop/ubuntu.yml
playbooks/install.py

[Minor] Node installer fixes to ansible playbooks.

[Fix] Add curl and wget to bench installer

---

bench/config/nginx.py
bench/config/production_setup.py
bench/config/templates/nginx.conf
playbooks/install.py
requirements.txt

- Added check to whether `brew` is installed on mac
- Added configuration to add `limit_conn_zone` Nginx directive to bench.
----

[Minor] Nginx rate limiting and Improvements to Bench Installer

---

bench/patches/v4/update_node.py

in case node exec does not exist find nodejs exec

Fixed node  patch

---

README.md

“with patched Qt" is specified for wkhtmltopdf

[minor] readme update

---

playbooks/develop/centos.yml
playbooks/develop/debian.yml
playbooks/develop/ubuntu.yml

[Fix] Install Python Ldap dependencies during bench installation

---

bench/config/common_site_config.py

Reverts frappe/bench#324
Else first site fails!

Revert "DNS Multitenancy by default"

---

bench/cli.py
bench/commands/setup.py
bench/utils.py
playbooks/production/change_ssh_port.yml

- `bench setup ssh-port [port]`

Added command to change SSH port

---

bench/app.py
bench/commands/update.py

added the option to git reset --hard instead of pull for the times u want to overide remote changes

[feature] add reset option to update

---

bench/app.py

less verbose app install

---

README.md

Please *preview the changes* to see a full list.

Proposed a number of changes in README.md

---

README.md

- For issue #333 - [Change Hostname]
- [Stopping Production] - temporarily pointed to github wiki article

Corrected Guides URLs

---

bench/app.py

@rmehta can u also fix the warnings to not include untracked files

[hotfix] fix update reset

---

bench/app.py
bench/cli.py
bench/commands/config.py
bench/commands/git.py
bench/commands/setup.py
bench/commands/update.py
bench/commands/utils.py
bench/config/common_site_config.py
bench/config/lets_encrypt.py
bench/config/nginx.py
bench/config/production_setup.py
bench/config/redis.py
bench/config/site_config.py
bench/release.py
bench/tests/test_init.py
bench/tests/test_setup_production.py
bench/utils.py
playbooks/install.py

Initiating discussion / pull request
Ran the script 2to3
installed bench on python2.7 and it works as expected.
Tried installing on python3.5 and it installs, bench start isn't working. `bench worker not found`

ran 2to3 script

---

bench/utils.py

Import hashlib library to use in the code below

Fix bug global hashlib is not defined

---

bench/utils.py

Make 'new-site' command respect passwords.txt #395
Relevant discuss post: https://discuss.erpnext.com/t/easy-install-features-example-use-case-automated-install-on-vm/23740

Make 'new-site' command respect passwords.txt #395

---

bench/config/lets_encrypt.py
bench/patches/v4/update_socketio.py

PR into develop branch
fixes #404

Letsencrypt fix develop

---

playbooks/develop/create_user.yml
playbooks/develop/includes/setup_bench.yml
playbooks/install.py

Add '--overwrite' flag to 'bench init' #396
Relevant discuss post: https://discuss.erpnext.com/t/easy-install-features-example-use-case-automated-install-on-vm/23740

Add '--overwrite' flag to 'bench init' #396

---

playbooks/install.py

Flags for mysql and admin password #394
Relevant discuss post: https://discuss.erpnext.com/t/easy-install-features-example-use-case-automated-install-on-vm/23740

Flags for mysql and admin password #394

---

bench/commands/setup.py

New Usage
```
bench setup sync-domains --site test.erpnext.com --domain "www.testerpnext.dev" --domain "www.testfrappe.dev"
```

[fix] accept domains as tuple argument

---

bench/utils.py

PR to maintain bench python 3 compatibility

python 3 compatible changes for `update_npm_packages`

---

bench/commands/__init__.py
bench/commands/utils.py
bench/prepare_staging.py

https://www.youtube.com/watch?v=ECDVGSZYsk8&feature=youtu.be

command to staging branch from develop brach

---

bench/commands/setup.py

- Adds a new site called bench_manager
- Adds a new app bench_manager
- Installs bench_manager app onto its namesake site

added setup_manager

---

bench/release.py

Prepare v{old_major}_x_x while releasing mjor version

---

playbooks/prerequisites/roles/mariadb/defaults/main.yml
playbooks/prerequisites/roles/mariadb/tasks/debian.yml
playbooks/prerequisites/roles/mariadb/templates/mariadb_centos.repo.j2
playbooks/prerequisites/roles/mariadb/templates/mariadb_ubuntu.list.j2

MariaDB 10.2

---

playbooks/prerequisites/roles/mariadb/tasks/debian.yml
playbooks/prerequisites/roles/mariadb/tasks/ubuntu.yml

mariadb playbook fix for ubuntu and debian

---

README.md

This PR add new bench logo to the README file
Below is the screenshot for the same .
Thanks

Update readme to add new bench logo

---

MANIFEST.in
bench/utils.py

pip-install-fix

---

bench/commands/__init__.py
bench/commands/setup.py

Migrate from one Python Version to Another

---

bench/commands/__init__.py

Expensive for Rollback but that's the way `virtualenv` creates environments and shutil.copytree is bad.

Backup, then Migrate Environments. (And not vice-versa)

---

playbooks/install.py
playbooks/roles/bench/tasks/main.yml
playbooks/roles/common/tasks/redhat_family.yml

- Install python3.6 in centos
- Handle python3 version for centos
fixes #613

develop fixes for centos

---

bench/commands/__init__.py
bench/commands/utils.py
bench/release.py

https://github.com/frappe/bench/issues/616
Now:
- Releasing from hotfix will update master and then push master to develop
- Releasing from develop will update master, system will not push release to hotfix

remove staging preparation and updation at release

---

playbooks/roles/mariadb/README.md
playbooks/roles/mariadb/defaults/main.yml
playbooks/roles/mariadb/handlers/main.yml
playbooks/roles/mariadb/tasks/centos.yml
playbooks/roles/mariadb/tasks/main.yml
playbooks/roles/mariadb/tasks/mysql_secure_installation.yml
playbooks/roles/mariadb/tasks/ubuntu-trusty.yml
playbooks/roles/mariadb/tasks/ubuntu-xenial.yml
playbooks/roles/mariadb/templates/mariadb_centos.repo.j2
playbooks/roles/mariadb/templates/mariadb_ubuntu.list.j2
playbooks/roles/mariadb/vars/main.yml

Pull-Request
---
--- 
- Motivation and Context (What existing problem does the pull request solve): Installation on Ubuntu 16.04
- Related Issue: https://discuss.erpnext.com/t/installation-failure-ubuntu-14-04-16-04-debian-9/37390 

mariadb fixes

---

playbooks/install.py

cryptography urllib3 fixes

---

playbooks/install.py

requests urllib3 crypto fixes

---

bench/commands/setup.py
bench/config/lets_encrypt.py

Include base domain too while setting up wildcard ssl

---

README.md
bench/app.py

fixes #653
fixes #515 
fixes #652

Multi fixes

---

completion.sh

- Supports bench and frappe commands completion
- Supports --site completion (only lists sites)

Autocompletion for bench (zsh and bash)

---

bench/commands/setup.py

fixed a casing issue where entering "N" would overwrite the site.
Signed-off-by: Chinmay Pai <chinmaydpai@gmail.com>

[minor] setup: fix overwrite existing site

---

playbooks/roles/common/tasks/debian_family.yml

Very handy! :smile:
https://github.com/frappe/frappe/pull/5009

Added pv as dependency for database restore

---

bench/release.py

- fixed the existing funtionality of prerelease

fix(prerelease): allow making prerelease for bench

---

README.md

Fixed minor typo error in the README

---

bench/release.py
bench/tests/test_init.py

- also included tests for the same

fix: proper semantic version bumping

---

bench/release.py

fix(release): don't fast-forward while merging

---

bench/app.py

Pull-Request
---
--- 
This corrects a typo in the message when update cannot be done due to local changes.

minor text improvements/typo

---

README.md

Addresses broken to installation wiki page for Linux.

Fix link to Linux install wiki page

---

bench/utils.py

@netchampfaris This commit seems to be breaking bench installation. Hence reverting this for now.

Revert "fix: Change ownership of all log and config files (#787)"

---

bench/commands/install.py
playbooks/roles/mariadb/defaults/main.yml

enhancement: provision to pass mariadb version

---

playbooks/install.py

fix: easy install script

---

README.md

Fix the manual install links for Mac and Linux guides.

Fix Install Links

---

.travis.yml
bench/app.py
bench/commands/make.py
bench/utils.py
playbooks/install.py

https://github.com/adityahase/frappe/tree/faster

fix: Allow skipping assets

---

bench/config/templates/nginx.conf

Same as https://github.com/frappe/frappe/pull/7074 for public files in production environment

fix(security): Force download html, svg and xml files

---

README.md

Pull-Request
Documentation change of the readme portion of the easy install to document in the open the `--contrainer` flag.
---
--- 
- Motivation and Context (What existing problem does the pull request solve): Resolve a lack in documentation where I had to dig inside the code to find out that an option was available.
- Related Issue: #811

fix(docs): README update ~ container flag for production install

---

README.md

Clarifies to the user that the script will by default create a new user with the name frappe if the flag is not used.
Pull-Request
---
--- 

docs: readme easyinstall username clarification

---

bench/app.py
bench/utils.py
requirements.txt

fix: git depth, fixed requirements

---

playbooks/install.py
playbooks/roles/common/tasks/debian.yml
playbooks/roles/common/tasks/debian_family.yml
playbooks/roles/common/tasks/ubuntu.yml

fix: setup libssl dependancy by checking distribution

---

README.md

fix(docs): README enhancements and references

---

bench/app.py
bench/utils.py

**what:** after pinning requirements, to avoid incompatible dependencies of dependencies, pass the -U flag
**why:** pinning erpnext, frappe dependencies

fix: add upgrade flags to pip install

---

bench/utils.py

added: user flag in `install_requirements` to install requirements at user level (specific to bench requirements)

fix: don't update bench dependencies in env

---

requirements.txt

chore: pinned requirements

---

requirements.txt

fix: add honcho and pin dependency

---

README.md

docs: add db_host and db_port options for new-site

---

bench/commands/update.py
bench/utils.py

* remove `download_chart_of_accounts()` method as it is not being used anywhere
* use `reload_module()` from six for flake8 fixes
closes #856

fix: remove unused method and use six to reload module

---

bench/commands/setup.py
bench/utils.py

Revert "fix(fonts): remove unused setup_fonts method"

---

bench/app.py
bench/commands/make.py
bench/utils.py

Skip build assets while running bench get-app

feat: skip build assets while doing get-app

---

bench/commands/update.py
bench/utils.py

Now, run `bench update` from anywhere!
also, auto stash changes in git for bench repo

feat: Bench update

---

playbooks/install.py

**fix:** updated sequence of package updates (prerequisites install issue in debian)
**fix:** os compatible paths
**chore:** breakdown install_bench in smaller functions

fix(easy_install): updated sequence of package updates

---

bench/utils.py

https://github.com/frappe/bench/pull/884

fix: git stash requires user details pre git v2.21

---

playbooks/install.py

**Changes:**
- easy install: install pip via system package manager
- easy install: recommends use Python 2 to run

fix(easy-install): install pip via pacman, minor fixes

---

bench/cli.py
bench/commands/__init__.py
bench/commands/update.py
bench/commands/utils.py
bench/utils.py

Revert "perf: faster bench"

---

bench/app.py
bench/commands/make.py
bench/commands/setup.py
bench/utils.py

**Features:**
- rollback on bench init {bench-name}
- if path already exists
- in case of some error that occurs during an init 
**Changes:**
- in case path already exists, `SystemError` is thrown instead of `ValueError`
- colors separated from `bench.utils.log` API
- `errno` imported instead of dependency on `os.errno` 
- ansible install depends on the pip used for the python version (optimistic install)

feat: rollback on bench init

---

.circleci/config.yml
.travis.yml
bench/utils.py

reference: https://github.com/pypa/pip/issues/7217

fix: pip pinned to 19.3.1 after v20 breaking

---

bench/utils.py

- [ x ] Bug Fix
See https://github.com/frappe/bench/commit/7fb1484b7f5dae561a098ab2a01c7f209664f626#diff-237d6b07e1835fbd8e51e251f66b2ec0 where the logic was changes to exclude handling this edge case

fix(init): handle edge case when ignore_exist is set and the path already exists

---

bench/utils.py

- pip install handling in case pip doesnt exist in `PATH`
- checks for bench requirements to be installed without the --user flag via pip in `in_virtual_env` function under `bench.utils`
**Error/Traceback:**
**references:** 
https://stackoverflow.com/questions/1871549/determine-if-python-is-running-inside-virtualenv

fix: virtualenv check for installing requirements

---

bench/cli.py

**What this PR does:** Execute bench commands in the subdirectories of any bench folder
**Before:**
**After:**

feat: execute bench commands in any sub directories of frappe-bench 

---

bench/commands/__init__.py
bench/commands/make.py

**Feat:** Directly install/update/remove packages from your env using bench pip
commands
---
**Install a new package in your `env`**  _(might be needed for testing)_
--- 
**Check which packages are installed in your `env`**
---
**For help using pip**
bench pip help [COMMAND]
bench pip [COMMAND] -h

feat: bench pip instead of using ./env/bin/pip

---

docs/easy_install.md

docs: fixes in easy_install.md

---

bench/commands/__init__.py
bench/commands/utils.py
bench/utils.py

* moved from __init__ to utils and updated sequence of installing
applications in env
* chanaged import namespaces

refactor: bench migrate-env command

---

.circleci/config.yml
.travis.yml
bench/utils.py

Revert "fix: pip pinned to 19.3.1 after v20 breaking"

---

bench/commands/setup.py
bench/config/lets_encrypt.py

fix(lets-encrypt): run command non interactively if flag passed

---

requirements.txt

**Reason:** pip2 dependency resolution failure
**Testing:**
- PY2, PY3

fix: pin dependencies of requirements

---

README.md
docs/bench_custom_cmd.md
docs/bench_usage.md

consists of bench usage docs. A consolidated list of all bench commands and brief description.

docs: added bench usage docs

---

.travis.yml
playbooks/install.py

import print from `__future__` for python2 to use print's `file=` param

chore: fix easy_install

---

.travis.yml
playbooks/install.py

fixes issue of PY2 run easy install in https://github.com/frappe/bench/pull/929

fix(easy-install): compatibility for easy install on PY2

---

bench/cli.py
bench/commands/__init__.py
bench/commands/config.py
bench/commands/git.py
bench/commands/install.py
bench/commands/make.py
bench/commands/setup.py
bench/commands/update.py
bench/commands/utils.py
bench/prepare_staging.py
bench/release.py
bench/utils.py

**Deprecated:**
- Commands:
- bench shell
- bench switch-to-master
- Functions:
- setup_auto_update
- pre_upgrade
**Refactored:**
- bench.commands.*
**Other Changes:**
- consistent formatting
- removed floating brackets from CLI output
- More verbose help for commands

refactor: bench commands help 

---

bench/app.py

https://discuss.erpnext.com/t/after-updating-v12-from-v11-having-problem-like-in-module-nothing-is-showing/58761/5

fix: remove deprecated pre_upgrade usage

---

bench/app.py
bench/commands/update.py

fix: switch branches "better"

---

README.md

Changed docker section to reference development and production docker images

chore: update README for docker

---

bench/utils.py

fix: Message per app when installing node deps

---

bench/cli.py
bench/utils.py

The check after the execution of every "bench" command. Excludes any custom or framework command calls.

feat: check for newer versions on PyPI

---

bench/utils.py

Fixed typo in "Open source..." sentence

docs: fixed typo on running update

---

install.py

Closes https://github.com/frappe/bench/issues/987

fix(playbooks): pre v5.1 compatibility for playbooks folder

---

README.md

update to env file location
sites is now docker volume

docs: fix readme docker section

---

playbooks/roles/common/tasks/redhat_family.yml

https://github.com/iusrepo/announce/issues/18

fix: ius repo

---

bench/app.py
bench/tests/test_init.py

Closes https://github.com/frappe/bench/issues/993

fix(get-app): allow ssh urls

---

bench/app.py
bench/commands/setup.py
bench/utils.py

fix: don't run yarn install while setting up py requirements

---

bench/app.py
bench/commands/config.py
bench/commands/setup.py
bench/config/nginx.py
bench/utils.py

chore: drop dead code

---

.travis.yml

Inspired by https://github.com/facebook/react/pull/2000 and arguably https://github.com/frappe/bench/pull/1009

chore: dont run travis for docs updates

---

.travis.yml

Reverts frappe/bench#1010
Doesn't work as expected.

Revert "chore: dont run travis for docs updates"

---

bench/playbooks/roles/dns_caching/handlers/main.yml
install.py

fix: provide smooth easy install experience

fix: ubuntu 20.04 easy install hang half way

---

install.py

- Update package lists and setup prereqs before setting up script dependencies 
- Use develop branch to clone bench instead of the outdated master branch
Fixes #1060

fix: Install Script fixes

---

install.py

Fixes https://github.com/frappe/bench/issues/1059

fix: Install wheel during ansible setup

---

bench/cli.py

Fixes https://github.com/frappe/bench/issues/1063

fix: Allow bench src as root

---

bench/commands/utils.py
bench/config/lets_encrypt.py

fix: backport of #1070

---

bench/playbooks/roles/mariadb/tasks/main.yml

fix: prevent error while bench new-site

fix: utf8mb4_general_ci

---

bench/config/common_site_config.py

---
Fixes https://github.com/frappe/bench/issues/737 raised by @mr-karan.
Issue: Feature Request
Gunicorn official docs [suggest the number of workers to be 2*cores + 1](http://docs.gunicorn.org/en/stable/design.html#how-many-workers).
Can we change the default worker count from the number of cores to the above suggested number?
---
---

build(config): Change default worker count

---

bench/playbooks/roles/bench/tasks/setup_erpnext.yml
install.py

---
Running `sudo python ./install.py --without-site` previously still created a site.
This fixes it and will skip creating a site if `--without-site` is specified.
---
---

fix(install): Obey --without-site

---

install.py

---
Upgrade Ansible to 2.8.15 (or later patch version)
---
---
Related to #1052.

fix: Upgrade Ansible to 2.8.15 (or later patch version)

---

install.py

Allow override of frappe_branch and erpnext_branch
Regardless of args.version (which always has a default set).
Additionally, print useful log of (non-credentials) variables used.
---
Currently `--frappe-branch` and `--erpnext-branch` is always ignored because `--version` has a default (`12`).
**Important:** Before this fix, it's not possible at all to install `version-13-beta` because of `install.py: error: argument --version: invalid int value: '13-beta`.
After this fix, even if version is something else, frappe-branch and erpnext-branch can be set manually.
---
> Explain the **details** for making this change. What existing problem does the pull request solve? The following …

fix(install): Allow override of frappe_branch and erpnext_branch

---

install.py

---
Until psycopg2-binary is available for aarch64 (Arm 64-bit), we'll need libpq and libssl dev packages to build psycopg2 from source
Fixes https://github.com/frappe/bench/issues/1084
---
---

fix(install): Install dev packages for Arm 64-bit

---

bench/config/templates/nginx.conf

fix: nginx proxy buffer

---

bench/playbooks/create_user.yml
bench/playbooks/roles/bench/tasks/main.yml
bench/playbooks/roles/bench/tasks/setup_inputrc.yml
bench/playbooks/site.yml
docs/easy_install.md
install.py

---
Actually, bench project is created in */home/{user}* and not according to passwd user directory. It should.
I have implemented a variable in install.py return home directory for args.user
this variable is used in ansible playbooks. This way bench is created is according folder and there's no breaking change.
---
---

fix: create bench folder in user directory

---

README.md

Fix link on menu to Basic Usage
---
Fix error link on Readme.MD
---
---

fix: Change link on Menu to Basic Usage

---

bench/utils.py

---
`dir` parameter of `compile_dir` was set to `../apps` which would only work if you're in sub-directory. It should be either `./apps` or using `os.path.join` which is OS agnostic. At present this is just not working as `../apps` directory can not be found. 
---
---
After:
Compiles all files as expected:
```
❯ fd -I -epyc | wc -l
5250
```

fix: use correct path for compiling py files
