frappe/bench

install_scripts/setup_frappe.sh

Enabling wkhtmltox for latest versions of ubuntu

wkhtmltox for trusty works ok on later versions of ubuntu

---

README.md
install_scripts/setup_frappe.sh

Script created when --setup-swap is provided as an command line argument to setup_frappe.sh, based on available RAM size, swap will be created if exists already, it will be ignored and setup will be continued as normally.

Automate swap partition setup for centos / ubuntu / debian servers

---

install_scripts/setup_frappe.sh

Some dependencies were replaced in Jessie and package software-properties-common ist needed too.

Debian Jessie fixes

---

bench/production_setup.py

In case symlink for supervisor.conf and nginx.conf already exists in the bench/config folder, then by pass the creation of symlinks.

[Fix] To disallow sym-link creation

---

bench/config/production_setup.py

- While setting up production, create symlinks for Supervisor and Nginx configuration files only if they are not symlinked.

[Fix] Create symlinks for supervisor and nginx only if they do not exist

---

bench/commands/setup.py

- While regenerating nginx configuration using `bench setup nginx` user is presented with a prompt. Adding `--force` to the command line will bypass this prompt.

[Fix] Added option to force upgrade nginx config file

---

bench/commands/setup.py

- Added option force regenerate the supervisor configuration
- Redis config regeneration does not require force.

[Fix] Added force option to supervisor config setup

---

install_scripts/setup_frappe.sh

Running Frappe setup script on a clean Debian installation caused following error.
```bash
admin@erpnext6:~$ admin@erpnext6:~$ sudo bash setup_frappe.sh --setup-production
admin@erpnext6:~$ sudo bash setup_frappe.sh --setup-production
Installing for debian 8 amd64
In case you encounter an error, you can post on https://discuss.frappe.io
Adding debian mariadb repo
Installing packages for debian. This might take time...
Installing wkhtmltopdf
Adding frappe user
Installing frappe-bench
Already using interpreter /usr/bin/python
INFO:bench.app:getting app frappe
Cloning into 'frappe'...
INFO:bench.app:installing frappe
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com
DEBUG:urllib3.connectionpool:"GET …
```

added npm, missing deb/ubuntu dependency

---

bench/cli.py
bench/commands/__init__.py
bench/commands/setup.py
bench/commands/utils.py
bench/config/lets_encrypt.py
bench/config/procfile.py
bench/config/production_setup.py
bench/config/templates/letsencrypt.cfg
requirements.txt

**New Command**: `sudo bench setup lets-encrypt [site-name]`
TODO: 
Fix for : 
https://github.com/frappe/bench/issues/218

Added command to setup Let's Encrypt for site

---

playbooks/develop/create_user.yml
playbooks/install.py

- Setuptools to be installed using bootstrap script instead of `pip`
- Do not get passwords while running script to setup development environment
- Added option to mention `repo-url` along with the branch
- `extra_vars.json` file moved to `/tmp` directory instead of user home directory
- create user ansible script needs to perform `chown` only in case of Linux.

Issues with Mac development bench installer

---

bench/__init__.py
bench/config/nginx.py
bench/config/templates/nginx.conf

- Wildcard SSL
In common_site_config.json:
```
"wildcard": {
"domain": "*.example.com",
"ssl_certificate": "/path/to/example.com.crt",
"ssl_certificate_key": "/path/to/example.com.key"
}
```
- Custom Domains
In site_config.json:
```
"domains": [
"other-example.com",
{"domain": "another-example.com", "ssl_certificate": "...", "ssl_certificate_key": "..."}
]
```

[refactor] nginx config now supports wildcard ssl and custom domains

---

install_scripts/setup_frappe.sh

Without mariadb repo check, setup script will fail for jessie 8.5 or any debian distro that has existing mariadb

mariadb repo check

---

bench/commands/utils.py
bench/utils.py

- Use `bench restart --web-workers` to only restart web workers.

[Minor] Added command to restart only web workers in supervisor 

---

bench/commands/utils.py

Fixed call to the routine `restart_supervisor_processes(bench_path='.', web_workers=web_workers)`

[Fix] Error

---

playbooks/develop/includes/setup_mariadb.yml

See https://github.com/frappe/bench/issues/285#issuecomment-239983969
Also disable exe bit on `setup_mariadb.yml`
Fixes #285

Ignore set root pass error if root password is already set

---

bench/app.py
bench/commands/__init__.py
bench/commands/git.py
bench/utils.py

New commands added:
1. bench remote-set-url `git_url`: Set upstream remote url for app
2. bench remote-reset-url:  Reset upstream remote url to frappe official
3. bench remote-urls: List apps remote url

Add git utility commands

---

bench/config/nginx.py

i found a bug when the user of the bench is currently using a dns-multitenant setup and he has multiple sites, and then he decides to switch to multiport setup, then all the sites present on the server get assigned the same port "80" and you can't change the port of any site due to the exception "Port 80 is being used by..."
so i fixed the bug by assigning a new port number that is not in use to every unassigned site, so afterwards the user can set his own port number for each site without having to face this exception and fail at this task

fixed a bug in default port for a site

---

bench/cli.py
bench/commands/setup.py
bench/utils.py
playbooks/production/setup_firewall.yml

Added `run_playbook` method to utils.py. Method exists in install.py, however, would have to make too many workarounds to re-use it. Currently dropped setup_firewall.yml inside `playbooks/production`, not sure of the best place. Command also checks if Ansible is installed.

Added command to setup firewall

---

playbooks/production/includes/setup_prod_env.yml

Fix for : https://github.com/frappe/bench/issues/232
Sets the InnoDB Buffer Pool Size to 50% of the total RAM during Production Setup

Set innodb buffer pool size in production setup

---

bench/config/redis.py

- Allocate 5% of total virtual memory available on the machine. Minimum allocated max_memory for Redis Cache is 50.

[Fix] Max memory given to redis cache should be dependent on virtual of the machine

---

bench/app.py

pull_all_apps calls a "git status" and checks if the response contains "nothing to commit, working directory clean". However, it seems that at least some versions of git output the message "nothing to commit, working directory clean". This causes bench update to not work in systems where the output message uses "tree" instead of "directory". This update is to allow both strings to be used.

Update pull_all_apps to use regex for check

---

bench/app.py

sys.exit causes bench update to stop bench update before taking backup and migrating the site

[fixes] fixes in pull_all_apps so, bench update can backup and sync

---

bench/utils.py

Get the following error when installing:
`./env/bin/pip install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
Obtaining pdfkit from git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
Updating ./env/src/pdfkit clone
Installing collected packages: pdfkit
Running setup.py develop for pdfkit
Complete output from command /home/strella/frappe-bench/env/bin/python -c "import setuptools, tokenize;__file__='/home/strella/frappe-bench/env/src/pdfkit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
File "<string>", line 1, in <module>
File "/home/strella/frappe-bench/env/src/pdfkit/setup.py", line 51, in <module>
'Topic :: Utilities' …

Installation fails for PDFKit - no module named six

---

.travis.yml
bench/tests/test_init.py
bench/utils.py
playbooks/install.py

After Travis changed its Trusy image, builds started failing. I traced it to the fact Travis `get_url` is making use of the system python interpreter (2.7.6). Python 2.7.6 does not support SNI thereby causing the download of `wkhtmltopdf` to fail.
- Upgrades ansible to 2.3.1
- Install urllib3, pyOpenSSL, ndg-httpsclient, pyasn1
- fix test case which was looking for mysqlclient-1.3.8 while our requirement in frappe/frappe is mysqlclient-1.3.10

Fix travis

---

bench/utils.py

`exec_cmd` causes TypeError on Python 3 (#451)

---

bench/commands/utils.py
bench/release.py

Release Sequence:
*. Release from `staging` branch.
- command:` bench release app-name --from-branch staging`
- merge `staging` branch to `master` branch
- merge release commit back to `staging` branch
- merge release commit to `develop` branch
- merge release commit to `hotfix` branch
*. Release from `hotfix` branch.
- command:` bench release app-name --from-branch hotfix`
- merge `hotfix` branch to `master` branch
- merge release commit back to `hotfix` branch
- merge release commit to `develop` branch
- merge release commit to `hotfix` branch
---
* configure common_site_config for release-bench
```
"branches_to_update": {
"staging": ["develop", "hotfix"],
"hotfix": ["develop", "staging"]
}
```

[fix] provision to handle release from staging branch

---

bench/commands/make.py
bench/utils.py

- Added skip-bench-mkdir as a parameter to the bench init command which skips frappe_bench mkdir if it already exists. 
- Added skip-redis-config-generation as a click option to the bench init command to skip the redis.generate_config method
- Added a try catch block to catch and except file exists Error 17 exception [see lines 56-61 in utils.py]

Added docker specific changes to bench

---

bench/utils.py

Bench port
Trying to install frappe with Python 3 yields following error traceback
```
File "/home/frappe/aditya/c6345ee5/3/bin/bench", line 11, in <module>
File "/home/frappe/aditya/c6345ee5/3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/frappe/aditya/c6345ee5/3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
return ep.load()
File "/home/frappe/aditya/c6345ee5/3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2316, in load
return self.resolve()
File "/home/frappe/aditya/c6345ee5/3/lib/python3.5/site-packages/pkg_resources/__init__.py", …
```

Replaced Py2 'except' syntax with Py3 syntax

---

bench/app.py
bench/commands/git.py
bench/config/redis.py
bench/patches/v4/update_node.py
bench/tests/test_init.py
bench/utils.py
vm/build.py

Bench port
Trying to install frappe with Python 3 after applying #466 yields following error traceback
```
File "/home/frappe/aditya/0a4b2ec7/3/bin/bench", line 11, in <module>
File "/home/frappe/aditya/0a4b2ec7/bench-repo/bench/cli.py", line 40, in cli
File "/home/frappe/aditya/0a4b2ec7/3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
File "/home/frappe/aditya/0a4b2ec7/3/lib/python3.5/site-packages/click/core.py", line 697, in main
File "/home/frappe/aditya/0a4b2ec7/3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
File …
```

Decode byte string returned by subprocess.check_output

---

bench/utils.py

Bench port
Trying to install frappe with Python 3 after applying #467 yields following error traceback
```
File "/home/frappe/aditya/b4e5700f/3/bin/bench", line 11, in <module>
File "/home/frappe/aditya/b4e5700f/bench-repo/bench/cli.py", line 40, in cli
File "/home/frappe/aditya/b4e5700f/3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
File "/home/frappe/aditya/b4e5700f/3/lib/python3.5/site-packages/click/core.py", line 697, in main
File "/home/frappe/aditya/b4e5700f/3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
File …
```

Use subprocess.check_output instead of Popen

---

bench/utils.py

Bench port
Trying to install frappe with Python 3 after applying #468 yields following error traceback
```
File "/home/frappe/aditya/4ab5ee90/3/bin/bench", line 11, in <module>
File "/home/frappe/aditya/4ab5ee90/bench-repo/bench/cli.py", line 40, in cli
File "/home/frappe/aditya/4ab5ee90/3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
File "/home/frappe/aditya/4ab5ee90/3/lib/python3.5/site-packages/click/core.py", line 697, in main
File "/home/frappe/aditya/4ab5ee90/3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
File …
```

Encode strings before passing to stdin.write

---

bench/utils.py

Bench port
Trying to install frappe with Python 3 after applying #469 yields following error traceback
```
File "/home/frappe/aditya/973b4a1c/3/bin/bench", line 11, in <module>
File "/home/frappe/aditya/973b4a1c/bench-repo/bench/cli.py", line 40, in cli
File "/home/frappe/aditya/973b4a1c/3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
File "/home/frappe/aditya/973b4a1c/3/lib/python3.5/site-packages/click/core.py", line 697, in main
File "/home/frappe/aditya/973b4a1c/3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
File …
```

Encode 'site' before hashing with hashlib.sha1

---

README.md
playbooks/develop/centos.yml
playbooks/develop/debian.yml
playbooks/develop/includes/setup_dev_env.yml
playbooks/develop/includes/setup_erpnext.yml
playbooks/develop/macosx.yml
playbooks/develop/ubuntu.yml

@rmehta, I'm creating a site called **site1.default** for default ERPNext installation. Is this approach okay or should we name the site in another way?
Works great on Ubuntu 16.04, I will now test on all other OSes.

Add default ERPNext installation to Easy Install script (develop)

---

playbooks/develop/includes/setup_bench.yml
playbooks/develop/includes/setup_erpnext.yml

- linked mysql.sock file mysql.pid file for compatibility with MaraiDB 10.2

Fixed playbook to be compatible with Mariadb 10.2

---

bench/config/templates/letsencrypt.cfg

With this modification I can now use bench setup lets-encrypt without any error.

Remove deprecated standalone-supported-challenges

---

playbooks/prerequisites/roles/nginx/tasks/main.yml
playbooks/production/includes/setup_bench_production.yml
playbooks/production/includes/setup_inputrc.yml

- mariadb 10.2 fix
- root user used instead of frappe_user fix
- selinux is set to permissive, in case of CentOS. This is needed to setup nginx
- bench is installed in the /home/username directory and not /home/root

Bench setup failed on production fix

---

playbooks/install.py

All of the *.yml Ansible files already have support for Debian 9. The only thing missing is an update to Ansible 2.4.1 and then changing the test up front. This has been tested on a out of box install on Debian 9.2.1.

Install debian 9 support

---

bench/app.py

This fix to handle branches with slashes, when using gitflow for example, you will have branches with names hotfix/branch-name. The bench commands fails with these branches names because it ignores anything before the slash. This fix would fix this issue to get the full name of the branch name

Fix determine current branch

---

bench/config/lets_encrypt.py

allows us to use yes | bench setup lets-encrypt {clientsite}
it gets rid of certbot prompt
Cert not yet due for renewal
You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
What would you like to do?
-------------------------------------------------------------------------------
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
automatically chooses option 1
By Default, most users would want to choose option 1 as let's encrypt lets a weekly limitation as to the number of certs you can get issued+renew. Cant really think of a usecase in which you want to replace the cert unless your cert is …

use certbot with -n option

---

MANIFEST.in

While `bench init`ing, `jinja2.exceptions.TemplateNotFound: Procfile` happens. This PR fixes it

fix no procfile found

---

bench/app.py

So this involves special handling for the `frappe` and `erpnext` docs apps: `frappe/frappe_io` and `erpnext/foundation`.
`get-app` only _clones_ the specified docs_app as well. Doesn't install
Issues:
------------------------------
---
--- 

[install] update frappe,erpnext docs apps to be installed

---

bench/config/nginx.py
bench/config/redis.py
requirements.txt

Works on linux. I need someone to test the following piece of code on MacOS and check if it correctly returns the total physical memory (RAM) in MBs in python.
```python
import os
(os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES')) / (1024 * 1024)
``` 
Platform to test before merge

removed psutil as a requirement

---

playbooks/roles/bench/tasks/setup_erpnext.yml

As mentioned in #657 admin and mysql root password with white-spaces
aren't recognized properly by shell adding single quotes around them
fixes this issue.

Add single quotes around password variables in ansible script

---

bench/app.py

Reverts frappe/bench#684
`frappe_theme` removed as a requirement for `foundation`.

Revert "get frappe_theme for foundation"

---

bench/tests/test_init.py
bench/tests/test_setup_production.py
playbooks/install.py
playbooks/roles/bench/tasks/setup_bench_production.yml
playbooks/roles/bench/tasks/setup_erpnext.yml
playbooks/roles/common/tasks/redhat_family.yml
playbooks/roles/mariadb/tasks/debian.yml
playbooks/site.yml

- in travis tests added check for the node_modules folder not found, since it was moved to frappe from v11 onwards
- added --without-erpnext flag to install only frappe
- identified but not yet fixed localctl failure on scaleway cloud (instant fix: apt install keyboard-configuration kbd console-data)
- fixed owner and permissions for bench.log in logs
- fixed mariadb set root password issue
- added libselinux-python to centos for localctl issues

multiple fixes

---

completion.sh

Doesn't yet provide auto-completion for frappe commands
Run `source completion.sh` to enable auto-completion on zsh and bash

Autocomplete for zsh and bash

---

bench/app.py
bench/commands/update.py

`reload()` is an inbuilt function in python2 but has been moved to `importlib` since python3.4.
source: https://docs.python.org/3/library/importlib.html#importlib.reload
`Signed-off-by: Chinmay Pai <chinmaydpai@gmail.com>`

[fix] reload(): use importlib for python3

---

bench/config/nginx.py

This is for a scenario when you have a single wildcard certificate for multiple domains. By default the nginx generation logic will only set the certs for domains that match the one set as the wildcard domain. 
However, by doing this, when you just set the domain as "*", the domain variable in the next line is set as empty string, which then is used in an `endswith`, which will always resolve `True`.

Allow user to set single wildcard certificate for all domains

---

bench/commands/utils.py
bench/release.py

Option to prevent frontporting code to new branches, for example
v11(staging-fixes) should go into v12(develop)
Reason: To offload tasks to bot for normal releases, which can be done
without conflicts on a regular basis. However the frontporting releases
need manual intervention since merge conflicts arise.

feat(release): option to prevent frontport

---

bench/app.py
bench/config/production_setup.py

- default caching of pip packages
- use `reload_supervisor` in `disable_production` (handles more cases, prevents tests from failing randomly)

fix: default caching of pip packages and other changes

---

bench/utils.py

pip installs the frappe apps instead of just their requirements.txt
It needs to be done so as to prevent update the app version for pip and
to prevent conflits for the dependencies in requirements.txt

fix: install app instead of requirements.txt

---

bench/cli.py
bench/utils.py

https://github.com/frappe/frappe/issues/6784
bench shows the wrong error message when frappe contains a syntax error
For example with `bench doctor`
```shell
Usage: bench [OPTIONS] COMMAND [ARGS]...
Error: No such command "doctor".
```
To correctly obtain the position of error one has to do the following
```shell
cd sites
../env/bin/python ../apps/frappe/frappe/utils/bench_helper.py frappe doctor
```
or as an alternative
```shell
cd sites
../env/bin/python -m frappe.utils.bench_helper frappe doctor
```
Which will then report error correctly
```python-traceback
File "../apps/frappe/frappe/utils/bench_helper.py", line 3, in <module>
import frappe
File "/Users/aditya/Frappe/frappe/apps/frappe/frappe/__init__.py", line 25
class _dict(dict)
^
SyntaxError: …
```

feat(error): Show SyntaxError found in frappe

---

bench/app.py

`bench remove-app <app>` exits with TypeError on python3.7
converting the subprocess output to string fixes this issue.

remove-app: fix for python3.7

---

bench/utils.py

Without this, after  ` sudo bench setup production ` file ownership of all log files isn't changed and requires human intervention.

fix: Change ownership of all log and config files

---

bench/cli.py

`get_frappe_commands` returns a list of valid frappe commands which is used to check if the user command is valid. But this is unnecessary because even without it bench can report the command not found error. This saves ~1 second.

perf: Remove unwanted check

---

bench/cli.py

Reverts frappe/bench#788
This breaks `bench init` and other bench commands

Revert "perf: Remove unwanted check"

---

bench/app.py
bench/utils.py

fix: Build assets only for downloaded app

---

playbooks/install.py

```
Installing collected packages: setuptools, urllib3, chardet, idna, certifi, requests, enum34, asn1crypto, pycparser, cffi, cryptography
Found existing installation: setuptools 0.9.8
Uninstalling setuptools-0.9.8:
Successfully uninstalled setuptools-0.9.8
Found existing installation: urllib3 1.10.2
Uninstalling urllib3-1.10.2:
Successfully uninstalled urllib3-1.10.2
Found existing installation: chardet 2.2.1
Uninstalling chardet-2.2.1:
Successfully uninstalled chardet-2.2.1
Found existing installation: requests 2.6.0
ERROR: Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
File "install.py", line 426, in <module> …
```

fix: requests package dependancy for centos

---

bench/commands/update.py

- While doing bench update, the system pulls the latest code first. Then it takes the backup of the sites, which can take a lot of time. In the meantime, the sites are not down and run the latest js code (which don't need to rebuild) and it can lead to errors. Thus taking a backup first before pulling the latest code.
- Another thing, as soon as migration finishes for one site, the site comes online. But supervisor reloaded only after migrating all sites. Which can lead to error due to inconsistent codebase and meta

fix: take backup before pulling the code and make site available after restarting the processes

---

playbooks/develop/debian.yml
playbooks/develop/ubuntu.yml

Pull-Request
---
--- 
This resolves the missing dependency issue (#808) for Debian/ubuntu for _dirmngr_.
See also https://discuss.erpnext.com/t/install-script-fails-on-debian-9-2019-07-29/51252

fix: adding dirmngr as dependency for debian, ubuntu playbooks

---

playbooks/install.py
playbooks/roles/common/tasks/debian_family.yml

---
Bug Fix: Cannot install on Ubuntu 18.04 LTS
---
**libssl1.0-dev** package name is replaced by **libssl-dev** .
Modified `install.py` and `debian_family.yml` files.

Replaced libssl1.0-dev packange name with libssl-dev

---

README.md

Removed the requirement for Python 2.7 and replaced with Python 3.6+. Removed reference of Python 3.5 not being recommended for production.

[Readme]Update Python info in pre-requisites

---

bench/utils.py

- [X ] Bug Fix
--- 
_bench init_ on Arch Linux fails to set up a crontab due to missing input argument. It shows the following error:
`INFO:bench.utils:setting up auto update
crontab: usage error: file name or - (for stdin) must be specified for replace`
This pull request modifies the setup script to detect Arch Linux and use the correct arguments resulting in the crontab being set-up successfully.

fix(Crontab): ArchLinux which uses the FreeBSD syntax

---

bench/commands/__init__.py
bench/commands/utils.py
bench/utils.py

Set redis hosts from command line.
bench set-redis-cache-host <host>:<port>/<db>
bench set-redis-queue-host <host>:<port>/<db>
bench set-redis-socketio-host <host>:<port>/<db>
port and db are optional

commands to set redis hosts

---

playbooks/install.py

i think some changes to the newer version of ansible api (2.9.0) causes mariadb installation to fail spectacularly. pinning the ansible version to 2.8.5 should fix this issue for now.

chore: pin ansible version to 2.8.5

---

bench/utils.py

Fixes "bench update" if bench is installed in a virtual environment

fix: bench update compatible venv installed pkg

---

bench/config/templates/nginx.conf

Avoid same site page being loaded with different urls:
For example with index.html:
https://sitename/index.html
https://sitename/index/
https://sitename/index
https://sitename
or a named page:
https://sitename/page.html
https://sitename/page/
https://sitename/page
This pull request solves that and do redirects 301 to the non trailing slash version:
"https://sitename/" will be 301 redirected to "https://sitename"
"https://sitename/index.html" will be 301 redirected to "https://sitename"
"https://sitename/pagename.html" will be 301 redirected to "https://sitename/pagename"
"https://sitename/pagename/" will be 301 redirected to "https://sitename/pagename"
More info about duplicated content and why it must be avoided:
https://support.google.com/webmasters/answer/66359?hl=en …

Nginx 301 redirect rules to avoid "duplicated content" for same site url variations

---

bench/config/nginx.py

fixes #873 where `unicode` keyword does not exist for python3:
```python-traceback
File "/usr/local/bin/bench", line 11, in <module>
File "/home/frappe/.bench/bench/cli.py", line 40, in cli
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
File …
```

fix: use six to check for string types

---

playbooks/install.py
playbooks/roles/common/tasks/debian.yml
playbooks/roles/nodejs/tasks/debian_family.yml

Pull-Request
---
--- 
- Easy Installer did not support Debian 10 Buster, so I changed the playbooks to support Debian 10.
- Related Issue: #831 
- Tested in a newly deployed Debian 10 Buster running on KVM and in a brand new deployed LXC Container (--container) also running fine.

feat(easy_install): add support for debian 10

---

bench/config/templates/nginx.conf

* drop support for TLSv1 and TLSv1.1, and add support for TLSv1.3
* disable all ciphers else for EECDH+AESGCM and EDH+AESGCM
* disable session ticketing
* use secp384r1 as certificate curve
* enable strict transport security with preloading
* enable xss-protection
[SSLLabs Result](https://www.ssllabs.com/ssltest/analyze.html?d=frappe.io) for frappe.io:

security(nginx): use only strong ciphers over ssl

---

bench/commands/setup.py
bench/utils.py

this method replaces existing system fonts directory under `/etc/fonts` and `/usr/share/fonts` with fonts that are probably obsolete by now and are no longer used.
removing this method so that it does not mess with anybody's system fonts.

fix(fonts): remove unused setup_fonts method

---

bench/commands/utils.py
bench/utils.py

Pull-Request
---
--- 
get_sites from bench differs from get_sites from frappe.utils generating errors when there is a "jupyter_notebooks" folder created by the "bench jupyter" command
If you used "bench jupyter" the bench creates a "jupyter_notebooks" folder inside "sites" where it stores all notebooks.
If you run "bench update" it does not run because it does not check if that folder is a real site and stops when doing site backups.
I just move the same site verifications into frappe.utils.get_sites to bench.get_sites and solve the issue.
None

bench.get_sites now do same checks to validate a site folder like frappe.utils.get_sites

---

playbooks/roles/bench/tasks/setup_bench_production.yml

Easy install fails if run again after config files exist. Adding the `--yes` flag in the playbooks will overwrite any existing config files.

fix(easy_install): overwrite config files

---

bench/cli.py
bench/commands/__init__.py
bench/commands/update.py
bench/commands/utils.py
bench/utils.py

What this does:
- caches Frappe commands in the bench folder in `.frappe-cmd` file
- re-generates the file on a run of `bench update` or manually by `bench clear-commands-cache`
- generates the cache file if not previously generated on execution of any bench command (like console, mariadb, etc) in the respective bench directory
New commands:
- generate-commands-cache
- clear-commands-cache
Misc. Changes:
- Run a single process to pip install prerequisites for new env setups
- Spawn processes as many as available CPUs for downloading translations

perf: faster bench

---

playbooks/install.py

Log files won't overwrite after each run of easy install script. 
Saved as `/tmp/logs/easy-install__{date}__{time}.log`
eg:
**date:** `2020-01-07` (YYYY-MM-DD)
**time:** `08:50` (24 hour format)
**file_name:** `/tmp/logs/easy-install__2020-01-07__08-50.log`
**_Note:_** UTC timestamps used
Misc. Additions:
- "Passwords don't match" message added
- Current distribution displayed while check

fix(easy_install): log files saved with timestamp

---

bench/cli.py
bench/commands/__init__.py
bench/commands/utils.py
bench/utils.py

**Feat:** 
1. New command "bench find [search-directory]"
- accepts a search directory parameter which defaults to home
- if run from a bench directory, it'll tell you so
- if run from any other directory without directory parameter then it'll find benches recursively from the search directory
2. Log print function "bench.utils.log"
- Depending on the level, `WARN` and `ERROR` tags will be appended to the message to directed stdout

feat: "bench find", print log api

---

bench/app.py

bench update assumes that erpnext is an installed app in the bench. This is a wrong assumption. This work around checks for the intersection of installed apps with  the list ['frappe', 'erpnext'] and only attempts to get the current branch of apps that occur in the intersection. This way, if erpnext is not installed (very likely for those using frappe only to build their own apps) there wont be an error when get_current_branch is called for erpnext. The need to perform the kind of check being performed in validate_branch is a strong case for considering apps being able to add "bench update" hooks in their hooks.py
See this topic https://discuss.erpnext.com/t/bench-update-error-no-such-file-or-directory-apps-erpnext/56932?u=chude_osiegbu
Pull-Request
---
--- 
- …

fix: validate branch in bench update

---

bench/commands/install.py

Update MariaDB version from `10.2` to `10.3` to match requirement in README.
By the way, is there any reason for the empty string being the default password and version?
```py
def install_maridb(mysql_root_password='', version=''):
```

fix: bump MariaDB version

---

playbooks/roles/bench/tasks/main.yml

fix broken permissions when `{{ frappe_user }}` owns `/root`

fix: chown frappe_user home directory

---

bench/config/lets_encrypt.py
requirements.txt

**What this does:** sets cron job under `root` user set for 1st of every month
**Reason:** `setup_crontab` failed silently on multiple tries on new Ubuntu 18.04 droplet and macOS 18.7.0
**Package Ref:** [python-crontab](https://gitlab.com/doctormo/python-crontab)

fix: setup cron job for renewing ssl certificate

---

requirements.txt

pip allows pinning requirement using [environment markers][0]
[0]: https://www.python.org/dev/peps/pep-0508/#environment-markers
improves: #932

chore: pin gitdb2 only for python < 3.4

---

bench/config/nginx.py
bench/utils.py

currently, running of `bench ` or `bench setup production` creates nginx conf files and asks for confirmation before overwriting them. in case user doesn't want to overwrite files, `setup production` and `lets-encrypt` is exitted abruptly and nginx isn't started again after. 
this happens because click abort was being used which sends a script termination signal in case of `n` instead of returning control to parent function.

fix: dont abort script if not overwriting scripts

---

bench/utils.py

* Async executions of multiple processes leads to various errors. Proposed solution to this is to execute blocking subprocesses. 
eg: get-app operation runs a "git clone" at the same time "pip install" is run. This causes failures as the folder either does not exist or isn't complete.
* readable formatting of system commands executed
Before:
After:

fix: random failings from subprocesses and command formatting

---

bench/commands/update.py
bench/utils.py

https://discuss.erpnext.com/t/bench-update-fails-due-to-no-bench-backup-option/58697
---
---
---

fix: "Error: no such option: --backup"

---

bench/app.py
bench/commands/config.py
bench/commands/update.py
bench/config/common_site_config.py
bench/config/redis.py
bench/utils.py

- removes `bench_update_on_update`
- removes `restart_update`
- removes `validate_pillow_dependencies`
- adds setup_env: find venv in current python and failure log 
- style fixes 
_Pending:_ docs update

chore: remove updating "bench tool" from update

---

bench/utils.py

changed default message prefix from `LOG` to `INFO`

chore: changed bench.utils.log API prefix 

---

bench/cli.py
bench/commands/__init__.py
bench/commands/utils.py
bench/utils.py

**What this does:**
- caches Frappe and all custom application commands in the bench folder under `.bench.cmd` file
- The cache is refreshed on `bench update` or manually by `bench clear-commands-cache`
- Generates the cache file if not previously generated on the execution of any bench command (like console, mariadb, etc) in the respective bench directory
**New commands:**
- generate-commands-cache
- clear-commands-cache
**Fixes:**
- Warnings not issued on `bench src` commands
- Removed wrong message on execution of `bench install`
**Misc. Changes:**
- Spawn processes as many as available CPUs for downloading translations
Improved port of #888

feat: faster bench

---

bench/utils.py

Using python-crontab library instead of manual processing
```
INFO:bench.utils:setting up backups
no crontab for revant
SUCCESS: Bench fbench initialized
crontab: usage error: file name or - (for stdin) must be specified for replace
Usage:
crontab [options] file
crontab [options]
crontab -n [hostname]
Options:
-u <user>  define user
-e         edit user's crontab
-l         list user's crontab
-r         delete user's crontab
-i         prompt before deleting
-n <host>  set host in cluster to run users' crontabs
-c         get host in cluster to run users' crontabs
-V         print version and exit
-x <mask>  enable debugging
Default operation is replace, per 1003.2
```
Reference: https://github.com/frappe/bench/pull/967#issuecomment-613731509

fix(backups): setup backups for bench sites

---

playbooks/roles/wkhtmltopdf/tasks/main.yml

Correcting checksum string for Debian 9
This is a hotfix to allow the installer to run on Debian 9. Withou this, it will fail with:
"template error while templating string: expected token 'end of print statement', got 'b0ab02aa6e17346af2f14ed0de807376de475ba90e1db3975f112fbd20bb'. String: {{ 1140b0ab02aa6e17346af2f14ed0de807376de475ba90e1db3975f112fbd20bb if ansible_architecture == \"x86_64\" else 5b2d15e738ac479e7a8ca6fd765f406c3684a48091813520f87878278d6dd22a }}"

fix(playbooks): wkhtmltopdf checksum string for debian 9

---

bench/app.py

Bug introduced in https://github.com/frappe/bench/pull/983

fix: install node modules only if package.json exists

---

bench/patches/v5/fix_user_permissions.py

Issues Fixed:
- after setting up new bench sudoers, `sudo bench setup supervisor` would fail as sudo doesn't get user password
- Supervisord restarted with the new configuration

fix: restart supervisord process after change in conf

---

bench/app.py
bench/cli.py
bench/commands/__init__.py
bench/utils.py

- Uses the same logger throughout bench
- `bench.log` found under `{bench/path}/logs`
- Logging levels:
**LOG:** explain what is happening in stages; eg: flushing redis, installing frappe, etc.
**DEBUG:** commands executed internally; eg: yarn install
**WARNING:** command executed with exit code 1, etc
**INFO:** default logs under bench commands executed
Example log:
```
2020-05-19 13:42:58,484 WARNING /Users/gavin/.pyenv/versions/3.7.7/bin/bench setup requirements --node executed with exit code 0
2020-05-19 13:43:02,143 INFO /Users/gavin/.pyenv/versions/3.7.7/bin/bench setup requirements
2020-05-19 13:43:02,147 DEBUG ./env/bin/pip install -q -U pip
2020-05-19 13:43:04,396 LOG installing frappe
```

fix(logging): cleaner bench logs

---

bench/app.py
bench/cli.py
bench/utils.py

- exit with appropriate return code
- remove stdout logging for LOG status; maintain data only in `bench.log`
- update deprecated logger `warn` API to `warning`

fix: exit with appropriate return code

---

bench/config/templates/Procfile

Directed stdout and stderr to respective files under `./logs`

fix: maintain worker and worker.error logfile in dev mode

---

bench/app.py

Fixes bug where `repo_name` is incorrectly extracted from git url

fix: trailing slash deleting apps folder

---

bench/playbooks/roles/common/tasks/ubuntu.yml

For ubuntu >=18.04 use libssl1.1 to support upgrade of OS since libssl1.0-dev is not supported by Ubuntu20.04 LTS.

fix(playbooks): Use libssl1.1 for ubuntu >=18.04 

---

bench/playbooks/roles/wkhtmltopdf/tasks/main.yml

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.focal_amd64.deb
Updating file to support Ubuntu20.04 LTS

feat(playbooks): wkthmltox for Ubuntu 20

---

bench/utils.py

All statements printed to `STDOUT` via `bench.utils.log`, will be added in `./logs/bench.log` too.

fix: populate bench.log via bench.utils.log

---

bench/cli.py

fix: don't show warning message in developer mode

---

bench/patches/patches.txt
bench/patches/v5/fix_backup_cronjob.py
bench/utils.py

---
---
**Problem:**
For newer benches, the crontab would be set to generate backups every _minute_ per 6 hours, as opposed to running it every 6 hours.
**Solution:**
Fix the crontab generation accordingly
**Reference:**
From the [`python-crontab`](https://pypi.org/project/python-crontab/) package documentation:
> Proceeding Unit Confusion
> It is sometimes logical to think that job.hour.every(2) will set all proceeding units to ‘0’ and thus result in “0 */2 * * *”. Instead you are controlling only the hours units and the minute column is unaffected. The real result would be “* */2 * * *” and maybe unexpected to those unfamiliar …

fix: run backups every 6 hours, rather than every minute per 6 hours

---

bench/config/templates/nginx.conf

`$proxy_add_x_forwarded_for` sets the user defined ip in the request. changing it to `$remote_addr` ensures that nginx sets the remote ip itself, disregarding user-specified ip from the request.

fix: use remote_addr instead of user-defined header ip

---

bench/commands/utils.py
bench/utils.py

Is it not awesome if anyone is not interested in viewing the process prefixed with the log on the terminal window.
By adding this option `--no-prefix` while `bench start` we can achieve it.
I feel this will help in finding any error or any log more easily and you can copy also from the terminal window efficiently without the process prefixed.

feat: bench start --no-prefix

---

bench/cli.py
bench/commands/setup.py
bench/config/production_setup.py
bench/config/supervisor.py
bench/tests/test_setup_production.py

fix: Update supervisord conf "better"

---

bench/playbooks/roles/nodejs/defaults/main.yml

Well, because this should've happened a long time ago.

fix: Bump Nodejs v8 => v12

---

install.py

- Fix faulty Debian 10 unsupported statement
- Change MariaDB default version installed to `10.4`
Fixes https://github.com/frappe/bench/issues/1045

fix(install): Show Debian 10 is supported, update MariaDB defaults

---

bench/cli.py
bench/commands/utils.py

Depending on which `bench` module Python gets while importing bench, `bench src` may give wrong results. In case the package of an older version is cached and gets imported first, the values may be different. This may even come up through some inconsistencies in the virtual environments you've set up.

fix: Show correct src of bench source

---

bench/cli.py
bench/utils.py

if bench commands are executed under the bench directory, they get populated under `./logs/bench.log`. In case of commands executed outside the bench directories, this PR adds a `NullHandler` to the existing bench logger.
Fixes #1057

fix: Don't show logs in stdout if command run outside bench directory

---

bench/cli.py
bench/tests/test_init.py

When no args given the command breaks, works fine with commands like
bench --version, bench init etc

fix: Handle no args passed in CLI

---

bench/playbooks/roles/wkhtmltopdf/tasks/main.yml

For Ubuntu 20.04 LTS and later
---
Support wkhtmltox arm64 architecture, which is supported starting 0.12.6.
Additionally, it's recommended to update to 0.12.6 for all architectures: https://github.com/frappe/bench/issues/1078
---
---
To support environments such as AWS Graviton1 & Graviton2.

fix(playbooks): Support wkhtmltox arm64 architecture

---

bench/commands/update.py
bench/utils.py

Move `compileall. compile_dir` after a pull updates.

fix: Run compileall in bench after update

---

.github/workflows/release.yml

Testing was done on TEST_PYPI
The release was supposed to be done on PYPI.
One of the renamings was missed
This PR fixes Renaming

fix: change TEST_PYPI to PYPI

---

bench/commands/make.py

Minor doc fix. Only changes help message of a flag.

docs: Update help message for --frappe-branch

---

bench/commands/setup.py

Fixed wrong help messages in `bench setup fail2ban --help` command.

fix: fail2ban help message

---

bench/app.py
bench/commands/config.py
bench/commands/setup.py
bench/config/__init__.py
bench/config/common_site_config.py
bench/config/lets_encrypt.py
bench/config/nginx.py
bench/config/procfile.py
bench/config/redis.py
bench/config/site_config.py
bench/config/supervisor.py
bench/config/systemd.py
bench/release.py
bench/utils.py

This doesn't look tasteful, but at least it's fast. Well, I'll let you decide if it's fast. This is how long a typical bench CLI invocation takes.
```
$ time bench --site speed.com execute frappe.ping  
0.69s user 0.09s system 100% cpu 0.770 total
```
We can improve this by not importing code that isn't executed e.g. Jinja, Requests, etc, and shed ~300ms.
```
$ time bench --site speed.com execute frappe.ping  
0.28s user 0.06s system 101% cpu 0.329 total
```
Python provides a non-invasive way to profile import times with [`-X importtime`](https://docs.python.org/3/using/cmdline.html#id5). Executing `bench` doesn't seem to be compatible with this flag but, we can create `main.py`
```python3
from bench.cli import cli
if __name__ == "__main__":
cli()
```
and execute
```
python -X importtime …
```

perf: Faster CLI

---

bench/commands/setup.py
bench/config/supervisor.py
bench/config/templates/supervisor.conf

skips redis configuration during `bench setup supervisor --skip-redis`
In case redis is not installed locally and used as a remote service it causes redis processes to fail with command not found.

feat: skip redis config during supervisor setup

---

bench/app.py
bench/config/supervisor.py
bench/config/systemd.py
bench/config/templates/supervisor.conf
bench/utils.py

- This PR removes support for versions 5 and lower of the Frappe Framework.
- Additionally removes unused functions and variables.

chore: remove support for older versions of frappe

---

bench/app.py

Saves disk space on production machines
---
---
> $ bench update --apps frappe --reset --pull
```
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/frappe/frappe
* branch            develop    -> FETCH_HEAD
Backing up sites...
...
$ git fetch --depth=1 --no-tags upstream develop
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/frappe/frappe
* branch            develop    -> FETCH_HEAD
$ git reset --hard upstream/develop
HEAD is now at a342ca2 fix: Get file name from path (#12437)
$ git reflog expire --all
$ git gc --prune=all
Counting objects: 3285, done.
Compressing objects: 100% (2627/2627), done.
Writing objects: 100% (3285/3285), done.
Total 3285 (delta 586), reused 3285 (delta 586)
$ …
```

feat: Keep repos shallow if --reset and shallow_clone are specified in bench update --pull
